- name: Install PostgreSQL repository
  package:
    name: "{{ item }}"
    disable_gpg_check: true
    state: present
  loop: "{{ repos_rhel }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']

- name: Install pgBackrest on RHEL-based systems
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_rhel_all + packages_rhel_postgresql_group }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
  become: true 

- name: Check if firewalld is running
  shell: systemctl is-active firewalld
  register: firewalld_status
  changed_when: false
  failed_when: false

- name: Open PostgreSQL ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ postgres_ports }}"
  when: 
    - ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
    - firewalld_status.stdout == 'active'
  become: true