- name: Install PostgreSQL repository
  package:
    name: "{{ item }}"
    disable_gpg_check: true
    state: present
  loop: "{{ repos_rhel }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']

- name: Install pgBackrest on RHEL-based systems
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_rhel_all + packages_rhel_postgresql_group }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']

- name: Open PostgreSQL and Patroni ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 5432
    - 8008
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
