- name: Set TLS dir owner 
  set_fact:
    pki_dir_owner: >-
      {{ 'postgres' if inventory_hostname in groups['postgres']
         else 'pgbackrest' if inventory_hostname in groups['pgbackrest']
         else 'root' }}

- name: Ensure TLS directory exists
  file:
    path: "{{ pki_dir }}"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"

- name: "Create a self signed certificates"
  include_tasks: "{{ pki }}.yml"  