- name: Install packages on RHEL-based systems
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_rhel_all }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
  become: true 
  
- name: Open etcd ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ etcd_ports }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
  become: true 