- name: Install PostgreSQL repository
  package:
    name: "{{ item }}"
    disable_gpg_check: true
    state: present
  loop: "{{ repos_rhel }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
  become: true 

- name: Install pgBackrest on RHEL-based systems
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_rhel_all + packages_rhel_pgbackrest_group }}"
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
  become: true 
