pg_version: 17
patroni_version: "3.3.1"
etcd_version: "v3.5.1"
pgbackrest_version: "2.54.2"


#certificates
pki: self_signed

#pgBackrest
pgbackrest_stanza: "default"
pgbackrest_backup_username: "pgbackrest"
pgbackrest_backup_password: "test"
pgbackrest_cipher_pass: "Yf8E4coA2SukDpWyOe9KXZhGbq/v1JNL7xMCRdmUg+TwPnLIhs6HjaYlFt3QzWOB"
pgbackrest_crontab_interval_full: "0 2 * * MON,WED,FRI,SUN"  # Full backup: Mon, Wed, Fri, Sun at 2 AM
pgbackrest_crontab_interval_diff: "0 2 * * TUE,THU,SAT"  # Diff backup: Tue, Thu, Sat at 2 AM
pgbackrest_host_protocol: ssh # ssh / tls


# PostgreSQL
patroni_replication_username: repl
patroni_replication_password: replication_password
patroni_superuser_username: postgres
patroni_superuser_password: postgres_password
